//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_SAR.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityVisitQuestionsReport
    {
        public int Id { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Si { get; set; }
        public Nullable<bool> No { get; set; }
        public Nullable<bool> Np { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> RealDate { get; set; }
    
        public virtual VisitSecurityReport VisitSecurityReport { get; set; }
    }
}
