//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_SAR.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitFlashReports
    {
        public int Id { get; set; }
        public string Bu { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> Antiquity { get; set; }
        public string TypeEmployee { get; set; }
        public string CategoryEmployee { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Position { get; set; }
        public string AccidentType { get; set; }
        public string Schedule { get; set; }
        public Nullable<System.DateTime> AccidentDate { get; set; }
        public Nullable<System.TimeSpan> AccidentTime { get; set; }
        public Nullable<int> WorkPlaceId { get; set; }
        public string DevelopedActivity { get; set; }
        public string DirectCause { get; set; }
        public string AffectedBodyPart { get; set; }
        public string NatureOfInjury { get; set; }
        public string IsSeriousAccident { get; set; }
        public string CouldBeSeriousAccident { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public Nullable<int> AccountId { get; set; }
        public int FlashAlertType { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual WorkPlaces WorkPlaces { get; set; }
    }
}
