//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_SAR.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitSecurityReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitSecurityReport()
        {
            this.SecurityVisitQuestionsReport = new HashSet<SecurityVisitQuestionsReport>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public Nullable<int> WorkPlaceId { get; set; }
        public Nullable<int> SecurityVisitId { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual SecurityVisit SecurityVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityVisitQuestionsReport> SecurityVisitQuestionsReport { get; set; }
        public virtual WorkPlaces WorkPlaces { get; set; }
    }
}
